[package]
name = "verification_specs"
description = "external specifications for crates used by verified code"
version = "0.1.0"
authors = ["Ramla-I <ijazramla@gmail.com>"]
# build = "../../build.rs"

[dependencies]
bit_field = "0.7.0"
volatile = "0.2.7"


[lib]
crate-type = ["rlib"]
